### ISSUE TITLE
By Phase/By Mode color toggle (WFRC)

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc-wasatch-choice#178]
Transportation Tab:
> ...we would like the ability for the user to click a control (ideally atop the layer/legend panel) that toggles the coloring from 'By Phase' to` 'By Mode' similar to how the awesome new RTP Projects map works. This does not need to include any of the advanced filter functionality as I think we'll direct people to the new map for that.

**Comment by nathankota** [comment]
The new idea/plan is to switch the WC map to use the RTP map.

### FY24 Q1 Sprint 1 Tasks:
- [ ] Obtain test RTP web map from Sarah L.
- [ ] Determine workload and next steps

**Comment by nathankota** [comment]
### Sprint 2 Tasks:
- [ ] onto resolving this enhancement

**Comment by stdavis** [comment]
Sent this to the client yesterday for feedback.
