### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nathankota** [agrc/wfrc-wasatch-choice#51]
Translate content, etc. to Spanish and/or other languages.

**Comment by stdavis** [comment]
@bgranberg or @msilski:
Which parts of the application would you like to be able to internationalize? Here's a list of options that I gathered upon first glance:
* "Wasatch Choice Map" title
* tag line (e.g. #wherematters) (would need to be done via config file)
* Tab names (would need to be done via config file)
* "Configure Map Tabs" dialog title, list labels and "Finish" button text
* About content (would also need to be done via the about config file)
* placeholder text in the search widget
* Filter widget
	* Pane title
	* Content (would have to be done via config)
* Project Information widget pane title and placeholder/instructions text ("Click on a feature...")
* "Wasatch Choice" logo

**Comment by msilski** [comment]
I think that's all of the text on the map - looks good to me. Bert and I need to decide how much of the source data should be translated, but that's on us.

@bert-granberg - would we need to produce a new poster in Spanish for the Vision tab? If the rest of the app text will be translated, then it would make sense to translate the poster, too. Are there plans to translate the poster into Spanish? We might need to reach out to Andrew, Ted, and maybe Penna Powers.

**Comment by stdavis** [comment]
@bgranberg & @msilski We'll need a Spanish version of the "Wasatch Choice" logo for this issue.

**Comment by stdavis** [comment]
I'm assuming that they don't care about translating the logo.
